---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blocky
  namespace: blocky
spec:
  interval: 15m
  chart:
    spec:
      chart: blocky
      version: 17.0.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Amsterdam

    credentials:
      minio:
        type: s3
        url: "${S3_URL}"
        bucket: "taloscluster"
        accessKey: "${S3_ACCESKEY}"
        secretKey: "${S3_SECRETKEY}"
        encrKey: "${S3_ENCRKEY}"

    service:
      dns:
        externalTrafficPolicy: Local
        type: LoadBalancer
        loadBalancerIP: ${IP_BLOCKY}

    # -- set the default DNS upstream servers
    defaultUpstreams:
      - tcp-tls:1.1.1.1:853
      - tcp-tls:1.0.0.1:853

    # -- set conditional settings
    conditional:
      mapping:
        - domain: thuis
          dnsserver: 192.168.1.1
        - domain: test.${DOMAIN}
          dnsserver: 192.168.1.157

    # -- set blocking settings using Lists
    blocking:
      # --  Add blocky whitelists
      # `default` name is reservered for TrueCharts included default whitelist
      # example shows the structure, though name should be changed when used
      whitelist:
        []
        # - name: default
        #  lists:
        #   - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/optional-list.txt
        #   - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
        #   - https://raw.githubusercontent.com/rahilpathan/pihole-whitelist/main/1.LowWL.txt

      # -- Blocky blacklists
      # `default` name is reservered for TrueCharts included default blacklist
      # example shows the structure, though name should be changed when used
      blacklist:
        []
        # - name: default
        #  lists:
        #   - https://big.oisd.nl/domainswild
        #   - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

      # -- Blocky clientGroupsBlock
      clientGroupsBlock:
        - name: default
          groups:
            - default

    k8sgateway:
      # -- list of processed domains
      domains:
        - domain: ${BASE_DOMAIN}
          # -- Optional configuration option for DNS01 challenge that will redirect all acme
          # challenge requests to external cloud domain (e.g. managed by cert-manager)
          # See: https://cert-manager.io/docs/configuration/acme/dns01/
          dnsChallenge:
            enabled: false
            domain: dns01.clouddns.com
      forward:
        enabled: false
        primary: tls://1.1.1.1
        secondary: tls://1.0.0.1
        options:
          - name: tls_servername
            value: cloudflare-dns.com

    queryLog:
      # optional one of: mysql, postgresql, csv, csv-client. If empty, log to console
      type: "postgresql"

    cnpg:
      main:
        cluster:
          singleNode: true
