---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik-upstream
  namespace: authentik-upstream
spec:
  interval: 15m
  chart:
    spec:
      chart: authentik
      version: 2025.4.0
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: enabled
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    authentik:
        secret_key: "vUf2u3qBdnLxGXbK2ZR+sZrxNVoA6dBwTCPOQzMgAxVw+hepnIXtsRibNzOyY9iYcEWXzdsoJYN9y8Po"
        error_reporting:
            enabled: false
        postgresql:
            password: "ThisIsNotASecurePassword"

    server:
        ingress:
            ingressClassName: internal
            enabled: true
            hosts:
                - authentik.${DOMAIN_0}
            annotations:
              cert-manager.io/cluster-issuer: domain-0-le-prod
              cert-manager.io/private-key-rotation-policy: Always
            tls:
              - hosts:
                  - authentik.${DOMAIN_0}
                secretName: authentik-tls-0

    postgresql:
        enabled: true
        auth:
            password: "ThisIsNotASecurePassword"
    redis:
        enabled: true
