---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-java
  namespace: minecraft-java
spec:
  interval: 15m
  chart:
    spec:
      chart: minecraft-java
      version: 22.34.11
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Amsterdam

    global:
      stopAll: false

    service:
      bluemap:
        enabled: true
        ports:
          bluemap:
            enabled: true
            protocol: tcp
            port: 8100

    modrinth:
      - fabric-api
      - lithium
      - bluemap
      - armor-poser:beta
      - cloth-config
      - servux
      - sdlink
      - craterlib
      - reusable-vault-blocks

    workload:
      main:
        podSpec:
          containers:
            main:
              #securityContext:
              #  allowPrivilegeEscalation: true
              #  privileged: false
              #  capabilities:
              #    add:
              #      - NET_RAW
              env:
                #  MAX_TICK_TIME: -1
                #  ENABLE_AUTOPAUSE: "true"
                #  AUTOPAUSE_KNOCK_INTERFACE: "eth0"
                #  AUTOPAUSE_TIMEOUT_EST: "1800"
                #  SKIP_SUDO: "true"
                STOP_SERVER_ANNOUNCE_DELAY: 60
                SERVER_PORT: "{{ .Values.service.main.ports.main.port }}"
                QUERY_PORT: "{{ .Values.service.main.ports.query.port }}"
                RCON_PORT: "{{ .Values.service.rcon.ports.rcon.port }}"
                ENABLE_QUERY: "true"
                EULA: "true"
                GUI: "false"
                SNOOPER_ENABLED: "false"
                OVERRIDE_SERVER_PROPERTIES: "true"
                DUMP_SERVER_PROPERTIES: "true"
                VERSION: "1.21.4"
                TYPE: "FABRIC"
                DIFFICULTY: "hard"
                MAX_PLAYERS: 20
                MAX_WORLD_SIZE: 50000
                ALLOW_NETHER: "true"
                ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
                ENABLE_COMMAND_BLOCK: "false"
                FORCE_GAMEMODE: "false"
                GENERATE_STRUCTURES: "true"
                HARDCORE: "false"
                MAX_BUILD_HEIGHT: 320
                SPAWN_ANIMALS: "true"
                SPAWN_MONSTERS: "true"
                SPAWN_NPCS: "true"
                VIEW_DISTANCE: 32
                MODE: survival
                MOTD: "\u00A74Boemeltrein's Minecraft Server\u00A7r\n         \u00A7bHappy \u00A7e2025"
                PVP: "true"
                LEVEL_TYPE: normal
                LEVEL: Utopia
                ONLINE_MODE: "true"
                MEMORY: 12G
                # The default password is randomly generated on each startup; however, a specific one can be set with RCON_PASSWORD.
                # RCON_PASSWORD: "secretrconpass"
                OPS: ${MINECRAFT_OPS}
                OVERRIDE_OPS: "true"
                ENABLE_WHITELIST: "true"
                WHITELIST: ${MINECRAFT_WHITELIST}
                OVERRIDE_WHITELIST: "true"
                ENABLE_ROLLING_LOGS: "true"
                # LOG_TIMESTAMP: "true"
                # ICON: http://..../some/image.png
                # OVERRIDE_ICON: true
                ALLOW_FLIGHT: "false"
                # CURSEFORGE_FILES: "lithium,fabric-api"
                # CF_API_KEY: ${MINECRAFT_CF_API_KEY}
                MODRINTH_PROJECTS: '{{ join "," .Values.modrinth }}'
                USE_FLARE_FLAGS: "false"
                USE_AIKAR_FLAGS: "true"
                USE_SIMD_FLAGS: "false"

            mcbackup:
              enabled: false

    persistence:
      data:
        enabled: true
        type: nfs
        path: /mnt/SSD_Cluster/app_minecraft_data
        server: 192.168.1.50

      backups:
        enabled: false

    ingress:
      bluemap:
        enabled: true
        primary: true
        ingressClassName: external
        annotations:
          nginx.ingress.kubernetes.io/auth-method: 'GET'
          nginx.ingress.kubernetes.io/auth-url: 'http://authelia.authelia.svc.cluster.local:9091/api/authz/auth-request'
          nginx.ingress.kubernetes.io/auth-signin: 'https://auth.${DOMAIN}?rm=$request_method'
          nginx.ingress.kubernetes.io/auth-response-headers: 'Remote-User,Remote-Name,Remote-Groups,Remote-Email'
        targetSelector:
          bluemap: bluemap
        hosts:
          - host: ${MINECRAFT_URL}
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: cloudflare

    resources:
      limits:
        cpu: 8000m
        memory: 16Gi
      requests:
        cpu: 10m
        memory: 50Mi
