---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ext-denon
  namespace: ext-denon
spec:
  interval: 15m
  chart:
    spec:
      chart: external-service
      version: 15.6.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Amsterdam

    service:
      main:
        type: ExternalIP
        externalIP: "192.168.1.30"
        ports:
          main:
            protocol: http
            port: 80

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: denon.${BASE_DOMAIN}
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: cloudflare
