apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:oCtGd/FxeQpJ0pDfWH/tvyAWTbVwxXQj62HuH21gCg88z+e2Zt7bnVPXTzzzHtZGDO54bKPiC2BCcREYsRnpqtyAkNg5318WlWG3u0yAOdy4ZbfNxjMmi8B++aBLWNVL0KFB2+/IBcOaZpuBoRXEZnJ6p+F5zA9HizZQnqSv/IHbl5r7llwzsQfEt/7BoF0WGIKxX/+RrZMIHgwlqKEzpHMSuT4jcBI1dABNeO5lhZ+96pQ/0zmP67L1IuI8GRthLkAadwOnJ7Rg7F8kgFl0jyWgarIk2QiTkiaFAQYZ5+tzm73NrVFG9hflCVC0br4DOed5AMqSvA35zJylHOMZnUs4Mp+eO4N+LYBynBWjjx1FSO5YshwdZFIHrz11d9Za,iv:yeLLInTBSYB5GUiK6r3uzd0hIPYZQq5zjWX7VrG2z94=,tag:yhmhXoRmK2uz/JP3lv1ULA==,type:str]
    identity.pub: ENC[AES256_GCM,data:VNq+e6lq1UBDznEZ74YTrQ+PlxIEx+c+xqIJSR+XzyxnnhsMaMSGEiRzmDLp81xf9jAsJ4xI4imnIYLgBRRERfD78POuOoVAhLHssyGkZ+Qqt1tNYbOzQxuDmpClE1FtTdL2/80pi5OXtbLZT7/fSceAXdyqOI8YvF4ueFCsz3h+18EYd3a/Uf6DS0ibCQd9dnbHAtqSswoum8VX0Y/+CpOMZU/k7j9UoFcNn5n8NQQBZ08i4pzS/kojK8h4IJvNoanmtIT3aE4q5hzmew==,iv:65P2n4T9fcVq9aKIme4NS80w5xI93MLdfrZpXnqiBC4=,tag:ARry0e4itKsDzVC1AOSxGg==,type:str]
    known_hosts: ENC[AES256_GCM,data:f3UeDIU9nPgJmkPnhPDY3RNQAqAVIRt9saqmII9/faJHoGS6Bl7+uDjuWX0T7xSo/Tike8fiSSqDk0TfzkmUU9AjBd1xAo+t57J/1JJKGOb3tMYAeM7fctOvp47NPbndAYhzCBgy2tZJdr9uGZ3E9mZgCOM3cI/rEA0IpEDDMGCQBvHdun5qD/yixJFsW5mr41uJiXXGJRqzjde/6KHxdWXowO9LH2MsTDhQ,iv:fpwUv+YrcgVKssm0E+4ZeXrZh7w72w6Gq2ZVYcHd8TQ=,tag:/zBli5OLFeQXSNyaPLjMmQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1yuqumghpr00wfv5t2fhr3lc8jng3gz6e575x2yafrzffdndsjexsczznte
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTngzeTVqYW93RVBpazlE
            TXMyNXlodGYyVWdsazNhZERoY1lvcGJYSDAwCjcwY0JyK2ordHlQRUdoV1k1bkdl
            dVdkUDcwQXZWYitCUERacGU4VUZndHcKLS0tIHJ6SlZYNjNtS3ZpRmFxYVNtTnVP
            YjlaY1dZUTlsVkZnQVYzN3FOSHRKWEUKaAhwVhKao7/PStnMZ/lE4agFXxtaZoqX
            nc2xb5/mB3//+bUEZgM7nn6X2Cdhm5sbXn5TpyKTm52zQPdIz1i84w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-19T08:21:15Z"
    mac: ENC[AES256_GCM,data:2cTQhPQrnS4Xb6mHSFZ5HtIzckVv8Lv359IDzLNDLaMmL5JdZQCtO9J0W8WX9Y/HASwTr85gmEkohhwEUzGSCpIQhGs9y19SWL/V9c/28b/euvEU2+I1/aDeytptBiAKmuIjVQt8CWiV04rTxM8dXXNrfRLj1SpyKFn07IIDZF0=,iv:bb4xAvnGXlDYUkzqEm68KpJD9oEkUIcKyjC2vKohZrI=,tag:ksIjzXXH64zldbySbE0SAQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
