apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:3TZInvCcU12AsBc3TltEsFvPqKVQpCVB+F7AT4KVpmGLRYkk6Ufhg59sN4Xb2VWBIIdpUhhhJLczn+5SUNfRiZrk5vKXesw4L7K3MM3x55UfJCzDhj/zvs/NFviS7PCANCH/j5TFip5XHTGGW2N0eFSMUYwEkpUdoWg5lbyI8uQNPW7z5PMdFgY4tgSASFfWjyhR+daBJd/UmHvlGkzOq27z//1J5W4ZnOoOj53jDoqNxcdeLLGLm1PE8QOeQVJ/Rs/hiE8CHMkYJIUZHZ8COId4Q+9QLDEK3DX69m6I/h8QcEceEa5w8uT4WDvKrz6Hc89UibQ5AkW5uZVNMHhODH0gQHhQZwM1DNMr7Hl9fAszwE0sy1ZDwUE/jr1/xkhy,iv:sn9BQ6Om5/rpGu1zrOo8kQx7eKQrrNyJJqJZtmVLzJU=,tag:+xiwBZ26EVG0jj8X89KR3A==,type:str]
    identity.pub: ENC[AES256_GCM,data:UTauZ2khDfQK75RE1W7CvBz3f3VDB8zv2Ivx7RPp7i8bBRhrPy/uIQYU21paC1jphsn0Hu6v6qddNHLH/kdRs9M3/413vWXfL5KARniSMH+AGuLEyNoFxgvM48RZtD5AqOhupPlUl9n3w3+j5Mn3MfddM5doNoUy8gIYEjh/9cRuVf2Eipe1K/GUIIKtJkEZ47wJfR1qETgItbq+d783rYpINMYWiFQ40QKPBaVEpcbX8OCzPY4afY4AaOulmabJMwF32lVDIVzT1xbJDg==,iv:trUSliFeNcy0HO/eajE7Ox2TOuoQsG9jGSy2gHBz5O4=,tag:bNeoFY0ZQQENjCdDqkA3aw==,type:str]
    known_hosts: ENC[AES256_GCM,data:e1sLsP+QWHnPkENQlQ7DYE1i5eTXC4agmTJweIgMw8EU9v/0agb+JPwVOsMHWVkDJ+B429Pr5khh5fn1J8sNQsR/bg/wZoiIRqmu3o5ymzs9nAdJDdp0/cWprYZgFQo2U8TqLynQp5xPiJ72JvD8zHUZhWYymkipgVexgp6/l1EyvlpZKsSDuL0f01nzvv4TECaaJ0Iji7746Ph7oligm9Dmg00gF6Rk6peX,iv:LOhEVoWEAKMcYeiGeYpv2/E5bLTxLO1NWZBQUg6HWDI=,tag:RK1nkO29E8gm7Ie9qgYx5w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1yuqumghpr00wfv5t2fhr3lc8jng3gz6e575x2yafrzffdndsjexsczznte
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUjdFK3NOSGFldlNTbXNY
            cks2MTBSOE1mbEdia1dFNmdRczVtQTZvLzJ3ClY1UWNUZ0RnSm14RXNScEFETTQy
            cWRTbUFFWmluNm9kbk5URk9ub0MvWmsKLS0tIE9heCtQd2txa2ZET05hVmhpZ3Qz
            Ty9scmJMOEQ3Z3RkR29xSEpJaXdQb2MKstM0uSad2vlCcWolj2HlZ2X4p7K3Vi8n
            fgt+Fxeiapvu+rHUgw2IgXoSSltOZxbfBA3UcZHDTpkKYahJZOlcsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-01T20:10:59Z"
    mac: ENC[AES256_GCM,data:53SUjlFgzDOR2oTcrYRSNdno/EXA0tDE0ckjeJqv7u/I0zZiYZq4Onsi7tA8jzBwBbz2eKcO8zqHqULVjcByH5zpY/ar0Wwl8i9f2iYSGQre5p2tfN5FZPwHVBLEyATlCYgiXdk+LGB1oos97kPZv7jCIIOGBng3fhG2tKFsQcw=,iv:UST5Mc+Xm1h9TUHEzIM7iISTV8bRG/Ghu9cig1LCCtw=,tag:c134PP5+vFOXHbBRBt9Jxw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
