apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:NpKS1DSP/QSRhLAcOxR2f/U36jjYHq4ZMxH1GjJuvpzu22PWZE19f7faCB6UJVOuIBZNo4D/wWQRid4orVt7ozJ3VZZGe4BMjNf77j4zQ7O2N4/9Fib5NmCeJe8PmXkWm+YvIfE10q0IgBQ99uYfRvEhYIK8lYyGlq9cJCKiybcAIa7IDGKXbgp21IFoFRDFfoZgKPj9IDtzWMsav+/gmKadQCWANV5nZzg0j3JaUgvpCeeDCin6KMRG9eZ0yKnqog0mlrXM1ecJ3TO1DR4cG+IzFXJBry90CWi1Y0Fx1fPagvQNOdxKdFLFxxbde3YPoZopAUNG53BiG/tCiMN2j1t970PYdANFUHydjCMYMhlkCz7YekdtgWmaDkkb57aH,iv:N0yJ+wnnczUh/F1xQjViqUgnDel5SdtyjeCjcw7/EJ4=,tag:Me7epEpg/wc2RedxUVxX0w==,type:str]
    identity.pub: ENC[AES256_GCM,data:czpeZfNr1MaMYMQk3tMo41AYba/mnEzqwdIjLG/+seSKpzm6DyZ0EqOipRIwzhEChcr07+SsoHtg0dFQNQZxvNW6EugonjQgsYQS6r0nsCTE5Rv/4Ho2f7EO5xgG7sWsozRLYhFo6ta0EMYdAeAti+7P4YXn4+AMimB1joywLUwn/5aFepesi8lv2cgVpj/rgaX7s0qkIApwrCttKZMauVB8WJPvW/rDv6vyKVBN1NRehI9jwk+Y6Dqeve51/iRImYk7c3c/v+cSKOE1BQ==,iv:FWrG4cW0WLn+l46Fqfle1oG9tu3Zq/Z1eDAKVc/4tak=,tag:WxzS56hN2QJZYPM82cq/Bw==,type:str]
    known_hosts: ENC[AES256_GCM,data:gvS6XW46MlRwZuc8IRBum7JHP3VD4W51yBnk8JskiUIFwHymUIqvJYrGp6/1fLNQ5U4OQrnxsVVPb64WLl/xFq3Epzi921HZYu71QC3ZOEXwAQFdEkaVV4TRiPqO4gxzFM+WNv1/bdEkZPx1tJxD6Z2jMtgRdv2CBTeMbAGi9ta9eLQzJTWzIl323+2re6CK5RAJb85uTlOlae+mg6VehUymjflNtEDuDICj,iv:Lmg1HEN/5755aKoZzk1kBxYkIc80dO2XVDaIW67PrbM=,tag:4/aXaJ1TvCiDAGbcra3qdQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1yuqumghpr00wfv5t2fhr3lc8jng3gz6e575x2yafrzffdndsjexsczznte
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxV2JBMXBmYkhWWmpOSElE
            YS9rRXhQUVVsOVpJOHl5VmZsdUpYSFptTHlnCmJQdWNCa0lRS2wybG1BUEUraTcv
            ZWNJYjQyRUN3ZmN0ckI2anRWY3h0MkkKLS0tICtLSTNZdjVOUTh1U0JSS2NYMkxC
            NzNuNXp2azNDaFlBNHFOOTJCNnBHTjAKqhobYT0ecazwtk1I8HjSK2BWzzIgPLaB
            SJk8uUhsx4f+BrO2BVHzXH0PrR98gBy8m5ULQT1CmXQioHQgUs+AGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-01T17:50:34Z"
    mac: ENC[AES256_GCM,data:Y3B+Qigmf0+OlwM4J+emPe1DVdLh86dIgyp7SjP5J1WELda16NOmbaaQc7cHxhiZ7w1+ThlFyTOjaPtubzfmB05WNomm/Z9Wn+n4i/iKZt4/52KLKHWHXFm4W+zdt+5Bf02FynOg0wrJsMi9InEggDPaLrNjdjqZ29jywloTqOQ=,iv:Yl4m7lSKj9KPINrNJ5dxzmuscz4CaIAfEcmMkfK5KXI=,tag:mpvLP97gSv6QQww9NExbAA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
