apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:cjwKHad/hp666fQPQz6q87blyVlSkyPtv6QepnzXL3PV2GNw2Jxp7vyPyI8HIpNv9RJz0ZM7Euro1ANAjvf5bga2omB1PCfiig8bErS9uG871dzbV1AQicSuTIMklhFggBZZIKMsni5XL7JyPLkm1ii2ErYevVPkPdKGtYC10Kx7rwsZ7gbYOHbEHokLbahn5s9o6qw5+AKnY6YNRzYykp0dE3PQP+VJA7a8EZCx/v4wzHr44nxZE5oG2psbYFyUY8E2V+JnoOGZ4SCXHwd9y1KOuYv+HoyDrCyxYWaOTJSJnr5jC+FDG4vJZYv6zwEaBDAt3n63EE7xjMuTmgxQlMtbJsqlsSKGyLvj0y+AMVbN52i7uJ1PLl+0n7VRYxHx,iv:sZ/YkPIw29caUvT13zYULQDq3MvyH8CUf7fgSMJTt2Y=,tag:jQxtZasEEWoGbetzxdPDfw==,type:str]
    identity.pub: ENC[AES256_GCM,data:Yu8aaqPm71d/HPL8wN6KZi8W/xwvuLrIh+CafD0XnRc1NbfjIRJGkkF4OYaS94txrAKJYhrFEdMVsqX84kklMG5mCzW1HsF65DjMedMqsc4GmpdJP4JvuMta3jUjB7XcJUej0go6FN5JCfdfg3PLccUz7s3pElYX484iZx+oLieYonoPUKvr6UbcSMmfQ+JSjMmMMaBYlqLBuvi59kW9MWlqRudAcI1RxlS/IHf3EeSuWbHEJrg1yC39t1rXAcVxnCRzM3xFnkJASRqyOg==,iv:qxFDfTrzwUfVPG3f5+3+WwScDGL6JmE4+1O3JPC9bi0=,tag:aGsVbRm0eu3/zquHOqB7iQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:JNZ4WCWDoF7W2vcKLT6BVIlOnoqc2u+RABZRqSxHxV5ubR1f3ORIcFk4FyIrP/h7hWO6ZDRnbV2BwzsLBjVQVVHm6qXGQoz+DBb9re0esTv57mFZ1WeR0T/DjNQ1jCplGYD/1qnOMv84L4HGc0oS/QZoEVwSILRdTk57nTdF/8fST45Fku4ODj4Kl3BLAKFJLSz/6de28OptaXf7/AdpPEgRzj+1Z3wanJea,iv:YWjvSlphWEA+QzkvN5Q/vRczDHmMtlOefZulFefcsbs=,tag:v15gyOO8EV8e/oKcKtyjPQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1yuqumghpr00wfv5t2fhr3lc8jng3gz6e575x2yafrzffdndsjexsczznte
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cFBiTkQxTHp1VFdCYkpk
            TmhQNG5aa0JLRTJERWRpL1lJM29weGs2b0hNCkd4cWFqSzNWOCs3RXE5ekJIcHJZ
            SS9wR2c0YmxxNDBQVVpYd2tqVC9HNnMKLS0tIGNUVTZOTTlKb29GWjRhWktUN0tq
            Q2R6NzVVRXlXcFE3QVJiTDNpQ1pOYlEKZl+PfhBramo7E9E2ZlLt78XOWd9IDrJv
            pwRmFLh0oJtjn52LVEUKG3asvS4hDsvAqFX+lsN8Ns9+9GPF5smqyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-20T00:29:19Z"
    mac: ENC[AES256_GCM,data:5huJBpjugtYJye6I2HHPgYGdxRx1ga8I9wXJR8Yhr3y+jSuqKMk1V+uCbNpete/I5suEJClMB4qGwbywzXvDhXJM0CbuCxJ98y/iIVSJKTTodskiHi51SBWY22bIKJ1d74YOcOqbUXvZ99PGmxFQXYoGseKKLflPC9ltpzIeRrs=,iv:1lwiX2mF3QjQ78vVOzY+tNwq923gENcbS1EJaG4swHM=,tag:BPQalAERGQ7V1ox1ZLvL2Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
