---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: webserver-dynmap
  namespace: webserver-dynmap
spec:
  interval: 15m
  chart:
    spec:
      chart: static-web-server
      version: 6.10.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Amsterdam

    global:
      stopAll: false

    ingress:
      main:
        enabled: true
        ingressClassName: external
        annotations:
          nginx.ingress.kubernetes.io/auth-method: 'GET'
          nginx.ingress.kubernetes.io/auth-url: 'http://authelia.authelia.svc.cluster.local:9091/api/authz/auth-request'
          nginx.ingress.kubernetes.io/auth-signin: 'https://auth.${DOMAIN}?rm=$request_method'
          nginx.ingress.kubernetes.io/auth-response-headers: 'Remote-User,Remote-Name,Remote-Groups,Remote-Email'
        hosts:
          - host: dynmap.${DOMAIN}
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: cloudflare

    persistence:
      dynmap:
        enabled: true
        type: nfs
        path: /mnt/SSD_Cluster/app_minecraft_data/dynmap/web
        server: 192.168.1.50
        mountPath: /dynmap
      config:
        enabled: false

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                SERVER_ROOT: "/dynmap"
