---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-router
  namespace: minecraft-router
spec:
  interval: 15m
  chart:
    spec:
      chart: minecraft-router
      version: 1.10.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Amsterdam

    global:
      stopAll: false

    service:
      main:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${IP_MINECRAFT}
        ports:
          main:
            enabled: true
            protocol: tcp
            port: 25565
          query:
            enabled: true
            protocol: udp
            port: 25565

    mcrouter:
      default: minecraft-java.minecraft-java.svc.cluster.local:25565
      mappings:
        - ${MINECRAFT_URL}=minecraft-java.minecraft-java.svc.cluster.local:25565
        - ${HERMITCRAFT_URL}=hermitcraft-java-minecraft-java.hermitcraft-java.svc.cluster.local:25565
        - borderhoarder.${DOMAIN}=minecraft-border-hoarder-minecraft-java.minecraft-border-hoarder.svc.cluster.local:25565
