---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metube
  namespace: metube
spec:
  interval: 15m
  chart:
    spec:
      chart: metube
      version: 15.4.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Amsterdam

    credentials:
      minio:
        type: s3
        url: "${S3_URL}"
        bucket: "taloscluster"
        accessKey: "${S3_ACCESKEY}"
        secretKey: "${S3_SECRETKEY}"
        encrKey: "${S3_ENCRKEY}"

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: metube.${BASE_DOMAIN}
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: cloudflare

    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: minio
            dest: #VolSync Destination (Restore)
              enabled: true
            src: #VolSync Source (Backup)
              enabled: true
      downloads:
        type: nfs
        server: 192.168.1.50
        path: /mnt/HDD_Cluster/Usenet/MeTube
