---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 15m
  chart:
    spec:
      chart: authelia
      version: 28.0.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Amsterdam

    global:
      stopAll: false

    credentials:
      minio:
        type: s3
        url: "${S3_URL}"
        bucket: "taloscluster"
        accessKey: "${S3_ACCESKEY}"
        secretKey: "${S3_SECRETKEY}"
        encrKey: "${S3_ENCRKEY}"

    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: auth.${DOMAIN}
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: cloudflare

    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: minio
            dest: #VolSync Destination (Restore)
              enabled: true
            src: #VolSync Source (Backup)
              enabled: true

    cnpg:
      main:
        cluster:
          singleNode: true
        # mode: recovery   # Set to 'recovery' when recovery from S3, also change the revisions
        backups:
          enabled: true
          credentials: minio
          retentionPolicy: "14d"
          # revision: "1"
        recovery:
          credentials: minio
          # revision: "1"

    workload:
      main:
        replicas: 1
        podSpec:
          containers:
            main:
              env:
                AUTHELIA_SESSION_SECRET: ${AUTHELIA_SESSION_KEY}
                AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: ${AUTHELIA_JWT_KEY}
                AUTHELIA_STORAGE_ENCRYPTION_KEY: ${AUTHELIA_ENCRYPTION_KEY}

    # All configuration options should be put under this. Supports all upstream options
    authelia:
      session:
        cookies:
          - domain: ${DOMAIN}
            authelia_url: https://auth.${DOMAIN}
      authentication_backend:
        # lldap setup
        # https://github.com/lldap/lldap/blob/main/example_configs/authelia_config.yml
        ldap:
          implementation: lldap
          address: ldap://lldap-ldap.lldap.svc.cluster.local:3890
          base_dn: dc=${DN},dc=${DC}
          user: uid=manager,ou=people,dc=${DN},dc=${DC}
          password: ${AUTHELIA_PASSWORD}
      notifier:
        smtp:
          address: submissions://${SMTP_HOST}:465
          username: ${SMTP_USER}
          password: ${SMTP_PASSWORD}
          sender: Authelia Admin <no-reply@${DOMAIN}>
          tls:
            server_name: ${SMTP_HOST}
      password_policy:
        standard:
          enabled: true
          min_length: 10
          max_length: 0
          require_uppercase: true
          require_lowercase: true
          require_number: true
          require_special: true
      access_control:
        rules:
          - domain:
              - "${MINECRAFT_URL}"
              - "dynmap.${DOMAIN}"
            policy: one_factor
            subject: "group:minecraft"
