---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 15m
  chart:
    spec:
      chart: home-assistant
      version: 27.5.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Amsterdam

    global:
      stopAll: false

    credentials:
      minio:
        type: s3
        url: "${S3_URL}"
        bucket: "taloscluster"
        accessKey: "${S3_ACCESKEY}"
        secretKey: "${S3_SECRETKEY}"
        encrKey: "${S3_ENCRKEY}"

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: homeassistant.${BASE_DOMAIN}
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: cloudflare

    homeassistant:
      trusted_proxies:
        - 172.16.0.0/16
        - 172.17.0.0/16

    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: minio
            dest: #VolSync Destination (Restore)
              enabled: true
            src: #VolSync Source (Backup)
              enabled: true
      p1meter:
        enabled: true
        type: device
        hostPath: /dev/serial/by-id/usb-FTDI_P1_Converter_Cable_A6X1Y2R3-if00-port0

    cnpg:
      main:
        cluster:
          singleNode: true
        mode: recovery # Set to 'recovery' when recovery from S3, also change the revisions
        backups:
          enabled: true
          credentials: minio
          retentionPolicy: "14d"
          revision: "1"
        recovery:
          credentials: minio
          # revision: "1"
