apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zwave-js-ui
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/zwave-js-ui/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
